{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b4464447_31045abd",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1547372
      },
      "writtenOn": "2023-11-07T15:56:42Z",
      "side": 1,
      "message": "LGTM!",
      "revId": "0d54bee2e4ad139ade64fc3565830674ec5296ac",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "57236519_e36741e2",
        "filename": "appengine/swarming/api_common.py",
        "patchSetId": 2
      },
      "lineNbr": 136,
      "author": {
        "id": 1002539
      },
      "writtenOn": "2023-11-07T02:33:23Z",
      "side": 1,
      "message": "There\u0027s a test that expects BadRequestException if the reason is too long. It was relying on datastore limit on indexed string size (which is 1500 chars, but I arbitrarily decided to limit this by 1000 instead, no one would need such long \"reason\" anyway...).",
      "range": {
        "startLine": 132,
        "startChar": 0,
        "endLine": 136,
        "endChar": 76
      },
      "revId": "0d54bee2e4ad139ade64fc3565830674ec5296ac",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b41d1fb4_ccf37990",
        "filename": "appengine/swarming/api_common.py",
        "patchSetId": 2
      },
      "lineNbr": 136,
      "author": {
        "id": 1529627
      },
      "writtenOn": "2023-11-07T03:28:39Z",
      "side": 1,
      "message": "Ack.",
      "parentUuid": "57236519_e36741e2",
      "range": {
        "startLine": 132,
        "startChar": 0,
        "endLine": 136,
        "endChar": 76
      },
      "revId": "0d54bee2e4ad139ade64fc3565830674ec5296ac",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}