{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "237ddfcd_7abd8131",
        "filename": "appengine/components/components/config/remote.py",
        "patchSetId": 1
      },
      "lineNbr": 271,
      "author": {
        "id": 1381059
      },
      "writtenOn": "2023-08-18T23:56:10Z",
      "side": 1,
      "message": "similarly, why not logging.error?",
      "range": {
        "startLine": 271,
        "startChar": 16,
        "endLine": 271,
        "endChar": 23
      },
      "revId": "1525bfa5c9caada95ad94234cb0d61e8e9c5f3e1",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e10dd269_9941cae9",
        "filename": "appengine/components/components/config/remote.py",
        "patchSetId": 1
      },
      "lineNbr": 271,
      "author": {
        "id": 1398165
      },
      "writtenOn": "2023-08-22T18:59:29Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "237ddfcd_7abd8131",
      "range": {
        "startLine": 271,
        "startChar": 16,
        "endLine": 271,
        "endChar": 23
      },
      "revId": "1525bfa5c9caada95ad94234cb0d61e8e9c5f3e1",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "9bc260d4_0903c6d2",
        "filename": "appengine/components/components/config/remote.py",
        "patchSetId": 1
      },
      "lineNbr": 301,
      "author": {
        "id": 1381059
      },
      "writtenOn": "2023-08-18T23:56:10Z",
      "side": 1,
      "message": "nit-nit: maybe this could just be moved to L257 as this is v1 specific if it\u0027s not too complicated so it\u0027s easier to clean up in the future?",
      "range": {
        "startLine": 301,
        "startChar": 35,
        "endLine": 301,
        "endChar": 74
      },
      "revId": "1525bfa5c9caada95ad94234cb0d61e8e9c5f3e1",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e7a85e3a_52268ff1",
        "filename": "appengine/components/components/config/remote.py",
        "patchSetId": 1
      },
      "lineNbr": 301,
      "author": {
        "id": 1398165
      },
      "writtenOn": "2023-08-22T18:59:29Z",
      "side": 1,
      "message": "Because the `get_ref_configs_async()` below also calls the same function, but it\u0027s url path is different. So have to pass the url_path. \n\nBut I can try to delete `get_ref_configs_async` in another CL and see if it will lead to any Swarming side tests failures",
      "parentUuid": "9bc260d4_0903c6d2",
      "range": {
        "startLine": 301,
        "startChar": 35,
        "endLine": 301,
        "endChar": 74
      },
      "revId": "1525bfa5c9caada95ad94234cb0d61e8e9c5f3e1",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "5171228e_11eaca21",
        "filename": "appengine/components/components/config/remote.py",
        "patchSetId": 1
      },
      "lineNbr": 301,
      "author": {
        "id": 1381059
      },
      "writtenOn": "2023-08-22T19:07:59Z",
      "side": 1,
      "message": "\u003e But I can try to delete get_ref_configs_async in another CL and see if it will lead to any Swarming side tests failures\n\n\nsgtm",
      "parentUuid": "e7a85e3a_52268ff1",
      "range": {
        "startLine": 301,
        "startChar": 35,
        "endLine": 301,
        "endChar": 74
      },
      "revId": "1525bfa5c9caada95ad94234cb0d61e8e9c5f3e1",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8d4cb8a7_f4a56480",
        "filename": "appengine/components/components/config/remote.py",
        "patchSetId": 1
      },
      "lineNbr": 310,
      "author": {
        "id": 1398165
      },
      "writtenOn": "2023-08-18T00:02:29Z",
      "side": 1,
      "message": "double checked. No `refs` related requests this year.",
      "range": {
        "startLine": 310,
        "startChar": 15,
        "endLine": 310,
        "endChar": 25
      },
      "revId": "1525bfa5c9caada95ad94234cb0d61e8e9c5f3e1",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "18092866_f05078b9",
        "filename": "appengine/components/components/config/remote_test.py",
        "patchSetId": 1
      },
      "lineNbr": 276,
      "author": {
        "id": 1398165
      },
      "writtenOn": "2023-08-18T00:02:29Z",
      "side": 1,
      "message": "Even in luci-config v1, the server replies an empty response instead of a 404 for NotFound err in Get_projects_configs API. So I assert the empty result in the corresponding v2 test - `test_get_project_configs_async_v2_not_found`",
      "range": {
        "startLine": 276,
        "startChar": 46,
        "endLine": 276,
        "endChar": 49
      },
      "revId": "1525bfa5c9caada95ad94234cb0d61e8e9c5f3e1",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}