{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "e1b93679_e5cb466d",
        "filename": "appengine/swarming/server/task_queues.py",
        "patchSetId": 1
      },
      "lineNbr": 508,
      "author": {
        "id": 1001907
      },
      "writtenOn": "2022-08-31T21:50:08Z",
      "side": 0,
      "message": "oh wow, so txn failures would re execute this...",
      "range": {
        "startLine": 508,
        "startChar": 13,
        "endLine": 508,
        "endChar": 19
      },
      "revId": "893d43b063d42230c074936654da36cfa5a809b9",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "fb9c31f0_660413fc",
        "filename": "appengine/swarming/server/task_queues.py",
        "patchSetId": 1
      },
      "lineNbr": 508,
      "author": {
        "id": 1002539
      },
      "writtenOn": "2022-08-31T22:22:56Z",
      "side": 0,
      "message": "yes, it was a bug planted by me in the previous refactoring\nthough datastore_utils.transaction_async doesn\u0027t do retries by default for some mysterious reasons",
      "parentUuid": "e1b93679_e5cb466d",
      "range": {
        "startLine": 508,
        "startChar": 13,
        "endLine": 508,
        "endChar": 19
      },
      "revId": "893d43b063d42230c074936654da36cfa5a809b9",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}